import QueryClientProvider from "@/components/providers/query-client";
import "./globals.css";
import { Inter, Lato, Orbitron } from "next/font/google";
import { ReactNode } from 'react'
import { Toaster } from 'react-hot-toast'

const font = Lato({ subsets: ["latin"] ,weight: ["400", "700"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <QueryClientProvider>
          {children}
          <Toaster position="top-right" />
        </QueryClientProvider>
      </body>
    </html>
  );
}
